version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: iba-backend
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - iba-backend:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5431}:5432'

volumes:
  iba-backend:
